index:
    path: /
    controller: App\Controller\StreakController::myStreaks

streaks_categories:
    path: /streaks-cats
    controller: App\Controller\StreakController::index


registro:
    path: /registro
    controller: App\Controller\UserController::register

streaks:
    path: /streaks
    controller: App\Controller\StreakController::AllStreaks
login:
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout


streak_creation:
  path: /new-streaks
  controller: App\Controller\StreakController::creation


streak_detail:
  path: /streak/{id}
  controller: App\Controller\StreakController::detail

do_streak:
  path: /do-streak/{id}
  controller: App\Controller\StreakController::do
